/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import CivitasDAO.MahasiswaDAO;
import CivitasDAO.MahasiswaDAO;
import OOP.Mahasiswa;
import OOP.Mahasiswa;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author ITBSS
 */
public class INDEX_Mahasiswa extends javax.swing.JFrame {
private int selectedId = -1;
    /**
     * Creates new form Index
     */
    public INDEX_Mahasiswa() throws SQLException {
        initComponents();
        this.setExtendedState(INDEX_Mahasiswa.MAXIMIZED_BOTH);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_dosen = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_upd = new javax.swing.JButton();
        btn_del = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_mahasiswa = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("CIVITAS - MAHASISWA");

        btn_dosen.setBackground(new java.awt.Color(0, 153, 153));
        btn_dosen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_dosen.setForeground(new java.awt.Color(0, 0, 0));
        btn_dosen.setText("CIVITAS - DOSEN");
        btn_dosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dosenMouseClicked(evt);
            }
        });

        btn_add.setBackground(new java.awt.Color(0, 255, 51));
        btn_add.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_add.setForeground(new java.awt.Color(0, 0, 0));
        btn_add.setText("ADD");
        btn_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_addMouseClicked(evt);
            }
        });

        btn_upd.setBackground(new java.awt.Color(51, 51, 255));
        btn_upd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_upd.setForeground(new java.awt.Color(0, 0, 0));
        btn_upd.setText("UPDATE");
        btn_upd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_updMouseClicked(evt);
            }
        });

        btn_del.setBackground(new java.awt.Color(255, 0, 51));
        btn_del.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_del.setForeground(new java.awt.Color(0, 0, 0));
        btn_del.setText("DELETE");
        btn_del.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_delMouseClicked(evt);
            }
        });

        table_mahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_mahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_mahasiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_mahasiswa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(334, 334, 334)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(564, 564, 564)
                                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(btn_upd, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(btn_del, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(544, 544, 544)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 425, Short.MAX_VALUE)
                                .addComponent(btn_dosen)
                                .addGap(67, 67, 67)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btn_dosen, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_del, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_upd, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
   public void loadData() throws SQLException {
    MahasiswaDAO mahasiswaDAO = new MahasiswaDAO();
    List<Mahasiswa> data = mahasiswaDAO.getData(); 
    String[][] list = new String[data.size()][11];
    SimpleDateFormat dateFormat = new SimpleDateFormat("d MMMM yyyy");

    for (int i = 0; i < data.size(); i++) {
        list[i][0] = String.valueOf(data.get(i).getId());
        list[i][1] = String.valueOf(data.get(i).getNik());
        list[i][2] = data.get(i).getNama();
        list[i][3] = data.get(i).getTempat_lahir();
        
        Date tanggalLahir = data.get(i).getTanggal();
        list[i][4] = tanggalLahir != null ? dateFormat.format(tanggalLahir) : "-";
        
        list[i][5] = data.get(i).getEmail();
        list[i][6] = data.get(i).getJenis_kelamin();
        list[i][7] = String.valueOf(data.get(i).getIps());
        list[i][8] = String.valueOf(data.get(i).getIpk());
        list[i][9] = data.get(i).getJurusan();
        list[i][10] = data.get(i).getAngkatan();
    }

    String[] columnName = {
        "ID", "NIK", "Nama", "Tempat Lahir", "Tanggal Lahir", 
        "Email", "Jenis Kelamin", "IPS", "IPK", "Jurusan", "Angkatan"
    };

    table_mahasiswa.setModel(new javax.swing.table.DefaultTableModel(list, columnName));
}

    
    private void btn_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addMouseClicked
    try {
         ADD_Mahasiswa add = new ADD_Mahasiswa (this);
         add.setVisible(true);
         add.setLocationRelativeTo(null);
     } catch (Exception e) {
         e.printStackTrace();
     }
    }//GEN-LAST:event_btn_addMouseClicked

    private void table_mahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_mahasiswaMouseClicked
    int selectedRow = table_mahasiswa.getSelectedRow();
   if(selectedRow != -1){
       selectedId = Integer.parseInt(table_mahasiswa.getValueAt(selectedRow, 0).toString());
   }
    }//GEN-LAST:event_table_mahasiswaMouseClicked

    private void btn_delMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_delMouseClicked
    if(selectedId != -1) {
        int confirmation = JOptionPane.showConfirmDialog(this, "Apakah ingin dihapus?", "Peringatan",
                JOptionPane.YES_OPTION);
        if (confirmation == JOptionPane.YES_OPTION){
            MahasiswaDAO mahasiswaDAO;
            try {
            mahasiswaDAO = new MahasiswaDAO();
            mahasiswaDAO.deleteMahasiswa(selectedId);
            JOptionPane.showMessageDialog(this, "Berhasil", "Suksess", JOptionPane.INFORMATION_MESSAGE);
            loadData();
            selectedId = -1;
            } catch (SQLException e){
                    JOptionPane.showMessageDialog(this, "Error", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    }//GEN-LAST:event_btn_delMouseClicked

    private void btn_updMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updMouseClicked
       if(selectedId != -1){
         try {
             MahasiswaDAO mahasiswaDAO = new MahasiswaDAO();
             Mahasiswa mahasiswa = mahasiswaDAO.getMahasiswaById(selectedId);
             if(mahasiswa != null){
                 UPDATE_Mahasiswa upd = new UPDATE_Mahasiswa(this, mahasiswa);
                 upd.setVisible(true);
                 upd.setLocationRelativeTo(null);
             }
         } catch (SQLException e){
                    JOptionPane.showMessageDialog(this, "Error", "Error", 
                    JOptionPane.ERROR_MESSAGE);
     }}
    }//GEN-LAST:event_btn_updMouseClicked

    private void btn_dosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dosenMouseClicked
    try {
        INDEX_Dosen index = new INDEX_Dosen();
        index.setVisible(true);
        index.setLocationRelativeTo(null);
        this.dispose();
    } catch (SQLException ex) {
      JOptionPane.showMessageDialog(this, "Error", "Error", 
                    JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btn_dosenMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INDEX_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INDEX_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INDEX_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INDEX_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new INDEX_Mahasiswa().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(INDEX_Mahasiswa.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_del;
    private javax.swing.JButton btn_dosen;
    private javax.swing.JButton btn_upd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_mahasiswa;
    // End of variables declaration//GEN-END:variables
}
